---
- name: prod configuration
  hosts: prod
  become: yes
  roles:
    - commonp
    - security

- name: build configuration
  hosts: build
  become: yes
  roles:
    - commonb
    - build
    - security
